# Site settings
title: Jake Fleming
email: jcbflmng@gmail.com
description: Thoughts and work related to product design.
baseurl: "/jakeFlemingDesign"
url: "http://jakefleming.net" # the base hostname & protocol for your site
twitter_username: jakeflem
github_username:  jakefleming
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title
